package com.king_sparkon_tracker.backend.model;

public enum AffiliatePlacement {
	OWNER_ADD_PRODUCT,
	OWNER_ADD_WORKER,
	WORKER_BARCODE_THRESHOLD,
	TRANSACTION_PAYMENT_PLAN,
	TIP_CLIENT_QR_SCAN,
	TIP_CLIENT_PAYMENT_LINK,
	TIP_CLIENT_PAYMENT_SUCCESS,
	TIP_CLIENT_EMAIL_VIEW,
	DASHBOARD_SIDEBAR,
	HOME_RECOMMENDATION
}
