package com.king_sparkon_tracker.backend.model;

public enum BillingAuditAction {
	PLAN_CREATED,
	PLAN_APPROVAL_PENDING,
	PLAN_ACTIVATED,
	PAYMENT_SUCCESS,
	PAYMENT_FAILED,
	SUBSCRIPTION_CANCELLED,
	SUBSCRIPTION_SUSPENDED,
	SUBSCRIPTION_EXPIRED,
	BUSINESS_DEACTIVATED,
	BUSINESS_REACTIVATED,
	ADMIN_OVERRIDE_ACTIVATED,
	ADMIN_OVERRIDE_DEACTIVATED,
	WEBHOOK_RECEIVED,
	WEBHOOK_DUPLICATE_SKIPPED,
	WEBHOOK_SIGNATURE_FAILED
}
