package com.king_sparkon_tracker.backend.finance;

public enum FinancialAccountCode {
	BUSINESS_WALLET_LIABILITY,
	STRIPE_CLEARING,
	PAYPAL_CLEARING,
	PLATFORM_CLEARING,
	PROMOTION_REVENUE,
	TICKET_PROMOTION_REVENUE,
	PAYOUT_CLEARING,
	OWNER_WITHDRAWAL_CLEARING
}
