steps:
  - id: Build Docker image
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    env:
      - DOCKER_BUILDKIT=1
    secretEnv:
      - APP_ENV
    args:
      - -c
      - |
        docker build \
          --progress=plain \
          --secret id=app_env,env=APP_ENV \
          -t gcr.io/$PROJECT_ID/king-sparkon-tracker-backend:$COMMIT_SHA \
          .

images:
  - gcr.io/$PROJECT_ID/king-sparkon-tracker-backend:$COMMIT_SHA

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/app_env/versions/latest
      env: APP_ENV
