apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: king-sparkon
  labels:
    app.kubernetes.io/name: king-sparkon-tracker-backend
  annotations:
    iam.gke.io/gcp-service-account: kst-backend-gsa@PROJECT_ID.iam.gserviceaccount.com
