package com.king_sparkon_tracker.backend.dto;

import com.fasterxml.jackson.annotation.JsonAlias;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Size;

public record AddProductBarcodeRequest(
		@Schema(description = "Optional stock unit code generated by King Sparkon when omitted.")
		@Size(max = 120)
		String unitCode,

		@Schema(description = "Reusable retail product barcode printed on the product.")
		@JsonAlias({ "barcode", "productBarcode" })
		@Size(max = 128)
		String barcode,

		@Schema(description = "Optional customer email reference for returnable claims.")
		@JsonAlias("referencee")
		@Email
		@Size(max = 255)
		String referenceEmail) {

	public AddProductBarcodeRequest(String barcode, String referenceEmail) {
		this(null, barcode, referenceEmail);
	}
}
