package com.king_sparkon_tracker.backend.exception;

public enum ErrorCode {
	VALIDATION_FAILED,
	AUTHENTICATION_FAILED,
	EMAIL_NOT_VERIFIED,
	FORBIDDEN,
	RESOURCE_NOT_FOUND,
	DUPLICATE_USERNAME,
	DUPLICATE_EMAIL_ADDRESS,
	DUPLICATE_BARCODE,
	INSUFFICIENT_STOCK,
	RATE_LIMIT_EXCEEDED,
	PAYMENT_FAILED,
	WEBHOOK_SIGNATURE_INVALID,
	WEBHOOK_DUPLICATE,
	IDEMPOTENCY_CONFLICT,
	BUSINESS_ACCESS_RESTRICTED,
	INTERNAL_ERROR
}
