create table businesses (
	id bigint generated by default as identity primary key,
	name varchar(255) not null,
	owner_id bigint,
	created_date timestamp not null default current_timestamp,
	modified_date timestamp not null default current_timestamp,
	constraint fk_businesses_owner foreign key (owner_id) references bekina_faso_users (id),
	constraint uk_businesses_owner unique (owner_id)
);

insert into businesses (name, owner_id, created_date, modified_date)
select concat(username, ' Business'), id, current_timestamp, current_timestamp
from bekina_faso_users
where privilege_id in (
	select id
	from privileges
	where name = 'BekinaFasoOwner'
);

alter table bekina_faso_users add column business_id bigint;

update bekina_faso_users
set business_id = (
	select id
	from businesses
	where businesses.owner_id = bekina_faso_users.id
)
where id in (
	select owner_id
	from businesses
	where owner_id is not null
);

update bekina_faso_users
set business_id = (
	select min(id)
	from businesses
)
where business_id is null
and exists (
	select 1
	from businesses
);

alter table bekina_faso_users
add constraint fk_bekina_faso_users_business
foreign key (business_id) references businesses (id);

create index idx_bekina_faso_users_business_id on bekina_faso_users (business_id);

alter table products add column business_id bigint;

update products
set business_id = (
	select min(id)
	from businesses
)
where exists (
	select 1
	from businesses
);

alter table products
add constraint fk_products_business
foreign key (business_id) references businesses (id);

create index idx_products_business_id on products (business_id);

alter table beverage_transactions add column business_id bigint;

update beverage_transactions
set business_id = (
	select business_id
	from bekina_faso_users
	where bekina_faso_users.id = beverage_transactions.owner_id
)
where owner_id is not null;

update beverage_transactions
set business_id = (
	select min(id)
	from businesses
)
where business_id is null
and exists (
	select 1
	from businesses
);

alter table beverage_transactions
add constraint fk_beverage_transactions_business
foreign key (business_id) references businesses (id);

create index idx_beverage_transactions_business_id on beverage_transactions (business_id);

alter table audit_logs add column business_id bigint;

update audit_logs
set business_id = (
	select min(id)
	from businesses
)
where exists (
	select 1
	from businesses
);

alter table audit_logs
add constraint fk_audit_logs_business
foreign key (business_id) references businesses (id);

create index idx_audit_logs_business_id on audit_logs (business_id);