CREATE TABLE contact_inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_name VARCHAR(160),
    business_name VARCHAR(255) NOT NULL,
    email_address VARCHAR(255) NOT NULL,
    phone_number VARCHAR(64),
    message VARCHAR(2000) NOT NULL,
    status VARCHAR(40) NOT NULL,
    confirmation_email_sent BOOLEAN NOT NULL DEFAULT FALSE,
    notification_email_sent BOOLEAN NOT NULL DEFAULT FALSE,
    failure_reason VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_contact_inquiries_created_at ON contact_inquiries(created_at);
CREATE INDEX idx_contact_inquiries_email_address ON contact_inquiries(email_address);
