create table privileges (
	id bigint generated by default as identity primary key,
	name varchar(64) not null unique
);

create table bekina_faso_users (
	id bigint generated by default as identity primary key,
	username varchar(255) not null unique,
	email_address varchar(255) not null unique,
	created_date timestamp not null,
	modified_date timestamp not null,
	password varchar(255) not null,
	privilege_id bigint not null,
	constraint fk_bekina_faso_users_privilege foreign key (privilege_id) references privileges (id)
);

create table products (
	id bigint generated by default as identity primary key,
	name varchar(255) not null,
	barcode varchar(255) not null unique,
	category varchar(64) not null,
	price numeric(12, 2) not null,
	stock_quantity integer not null
);

create table beverage_transactions (
	id bigint generated by default as identity primary key,
	date timestamp not null,
	type varchar(16) not null,
	employee_id bigint not null,
	owner_id bigint not null,
	constraint fk_beverage_transactions_employee foreign key (employee_id) references bekina_faso_users (id),
	constraint fk_beverage_transactions_owner foreign key (owner_id) references bekina_faso_users (id)
);

create table transaction_items (
	id bigint generated by default as identity primary key,
	transaction_id bigint not null,
	product_id bigint not null,
	quantity integer not null,
	unit_price numeric(12, 2) not null,
	constraint fk_transaction_items_transaction foreign key (transaction_id) references beverage_transactions (id),
	constraint fk_transaction_items_product foreign key (product_id) references products (id)
);

create index idx_products_barcode on products (barcode);
create index idx_beverage_transactions_date on beverage_transactions (date);
create index idx_transaction_items_transaction_id on transaction_items (transaction_id);
create index idx_transaction_items_product_id on transaction_items (product_id);