create table if not exists refresh_tokens (
	id bigint generated by default as identity primary key,
	user_id bigint not null,
	token_hash varchar(64) not null,
	issued_at timestamp with time zone not null,
	expires_at timestamp with time zone not null,
	revoked_at timestamp with time zone,
	replaced_by_token_hash varchar(64),
	created_ip varchar(64),
	user_agent varchar(512),
	constraint fk_refresh_tokens_user foreign key (user_id) references tracker_users (id)
);

create unique index if not exists ux_refresh_tokens_token_hash on refresh_tokens (token_hash);
create index if not exists idx_refresh_tokens_user_active on refresh_tokens (user_id, revoked_at, expires_at);
