ALTER TABLE tracker_users ADD COLUMN IF NOT EXISTS profile_picture_url VARCHAR(2048);
ALTER TABLE ticket_events ADD COLUMN IF NOT EXISTS poster_photo_url VARCHAR(2048);

CREATE TABLE IF NOT EXISTS ticket_event_workers (
    event_id VARCHAR(64) NOT NULL,
    worker_id VARCHAR(64) NOT NULL,
    PRIMARY KEY (event_id, worker_id)
);

CREATE TABLE IF NOT EXISTS ticket_event_affiliates (
    event_id VARCHAR(64) NOT NULL,
    affiliate_id VARCHAR(64) NOT NULL,
    PRIMARY KEY (event_id, affiliate_id)
);

CREATE TABLE IF NOT EXISTS business_account_ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL,
    entry_type VARCHAR(40) NOT NULL,
    status VARCHAR(24) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    balance_after NUMERIC(14, 2) NOT NULL,
    provider VARCHAR(40),
    provider_reference VARCHAR(180),
    checkout_url VARCHAR(2048),
    description VARCHAR(1000),
    created_by VARCHAR(255) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_date TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_business_account_ledger_business_created ON business_account_ledger_entries (business_id, created_date DESC);
CREATE INDEX IF NOT EXISTS idx_business_account_ledger_business_status ON business_account_ledger_entries (business_id, status);
