alter table job_seeker_profiles
    add column profile_visible_to_businesses boolean not null default false;

create table job_profile_access_requests (
    id bigint generated by default as identity primary key,
    application_id bigint not null,
    business_id bigint not null,
    owner_id bigint not null,
    applicant_id bigint not null,
    status varchar(24) not null,
    request_message varchar(1000),
    created_date timestamp not null,
    modified_date timestamp not null,
    responded_date timestamp,
    constraint uk_job_profile_access_application unique (application_id),
    constraint fk_job_profile_access_application foreign key (application_id) references job_applications (id),
    constraint fk_job_profile_access_business foreign key (business_id) references businesses (id),
    constraint fk_job_profile_access_owner foreign key (owner_id) references tracker_users (id),
    constraint fk_job_profile_access_applicant foreign key (applicant_id) references tracker_users (id)
);

create index idx_job_profile_access_applicant_created on job_profile_access_requests (applicant_id, created_date);
create index idx_job_profile_access_business_created on job_profile_access_requests (business_id, created_date);
create index idx_job_profile_access_application_status on job_profile_access_requests (application_id, status);
