create table job_seeker_profiles (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    highest_qualification varchar(40) not null,
    interested_job_one varchar(120) not null,
    interested_job_two varchar(120),
    interested_job_three varchar(120),
    interested_job_four varchar(120),
    interested_job_five varchar(120),
    experience varchar(40) not null,
    about varchar(2000) not null,
    created_date timestamp not null,
    modified_date timestamp not null,
    constraint uk_job_seeker_profiles_user unique (user_id),
    constraint fk_job_profiles_user foreign key (user_id) references tracker_users (id)
);

create table job_posts (
    id bigint generated by default as identity primary key,
    business_id bigint not null,
    owner_id bigint not null,
    title varchar(180) not null,
    starting_date date not null,
    closing_date date not null,
    job_description varchar(4000) not null,
    years_of_experience_required varchar(40) not null,
    job_post_file_url varchar(2048),
    estimated_salary numeric(14, 2),
    currency varchar(8) not null,
    status varchar(24) not null,
    created_date timestamp not null,
    modified_date timestamp not null,
    constraint fk_job_posts_business foreign key (business_id) references businesses (id),
    constraint fk_job_posts_owner foreign key (owner_id) references tracker_users (id)
);

create table job_applications (
    id bigint generated by default as identity primary key,
    job_post_id bigint not null,
    applicant_id bigint not null,
    profile_id bigint not null,
    status varchar(32) not null,
    resume_url varchar(2048) not null,
    certificate_urls varchar(4000),
    created_date timestamp not null,
    modified_date timestamp not null,
    viewed_date timestamp,
    decision_date timestamp,
    constraint uk_job_applications_post_applicant unique (job_post_id, applicant_id),
    constraint fk_job_applications_post foreign key (job_post_id) references job_posts (id),
    constraint fk_job_applications_applicant foreign key (applicant_id) references tracker_users (id),
    constraint fk_job_applications_profile foreign key (profile_id) references job_seeker_profiles (id)
);

create table job_interviews (
    id bigint generated by default as identity primary key,
    application_id bigint not null,
    job_post_id bigint not null,
    business_id bigint not null,
    applicant_id bigint not null,
    interview_date timestamp not null,
    interview_description varchar(2000) not null,
    interview_expires_at timestamp not null,
    business_address varchar(1024) not null,
    status varchar(24) not null,
    created_date timestamp not null,
    modified_date timestamp not null,
    responded_date timestamp,
    constraint uk_job_interviews_application unique (application_id),
    constraint fk_job_interviews_application foreign key (application_id) references job_applications (id),
    constraint fk_job_interviews_post foreign key (job_post_id) references job_posts (id),
    constraint fk_job_interviews_business foreign key (business_id) references businesses (id),
    constraint fk_job_interviews_applicant foreign key (applicant_id) references tracker_users (id)
);

create index idx_job_posts_business_created on job_posts (business_id, created_date);
create index idx_job_posts_status_closing on job_posts (status, closing_date);
create index idx_job_applications_applicant_created on job_applications (applicant_id, created_date);
create index idx_job_applications_business_created on job_applications (job_post_id, created_date);
create index idx_job_interviews_applicant_date on job_interviews (applicant_id, interview_date);
create index idx_job_interviews_business_date on job_interviews (business_id, interview_date);
