CREATE TABLE IF NOT EXISTS api_idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(128) NOT NULL,
    request_scope VARCHAR(96) NOT NULL,
    actor_username VARCHAR(255) NOT NULL,
    business_id BIGINT,
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL,
    response_body TEXT,
    response_type VARCHAR(512),
    http_status INTEGER,
    failure_reason VARCHAR(1000),
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_api_idempotency_scope_actor_key UNIQUE (request_scope, actor_username, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_api_idempotency_status_expiry
    ON api_idempotency_records (status, expires_at);
CREATE INDEX IF NOT EXISTS idx_api_idempotency_business_created
    ON api_idempotency_records (business_id, created_at DESC);

CREATE TABLE IF NOT EXISTS financial_journals (
    id VARCHAR(64) PRIMARY KEY,
    business_id BIGINT NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    source_reference VARCHAR(180) NOT NULL,
    description VARCHAR(1000),
    currency VARCHAR(3) NOT NULL,
    immutable_hash VARCHAR(64) NOT NULL,
    posted_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    CONSTRAINT fk_financial_journal_business FOREIGN KEY (business_id) REFERENCES businesses(id),
    CONSTRAINT uk_financial_journal_source UNIQUE (business_id, source_type, source_reference)
);

CREATE TABLE IF NOT EXISTS financial_ledger_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_id VARCHAR(64) NOT NULL,
    line_number INTEGER NOT NULL,
    account_code VARCHAR(80) NOT NULL,
    entry_side VARCHAR(12) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    memo VARCHAR(700),
    CONSTRAINT fk_financial_line_journal FOREIGN KEY (journal_id) REFERENCES financial_journals(id),
    CONSTRAINT uk_financial_line_number UNIQUE (journal_id, line_number),
    CONSTRAINT chk_financial_line_amount CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_financial_journal_business_posted
    ON financial_journals (business_id, posted_at DESC);
CREATE INDEX IF NOT EXISTS idx_financial_line_account
    ON financial_ledger_lines (account_code, journal_id);

CREATE TABLE IF NOT EXISTS stock_reservations (
    id VARCHAR(64) PRIMARY KEY,
    business_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    transaction_id BIGINT,
    payment_reference VARCHAR(180) NOT NULL,
    idempotency_key VARCHAR(128),
    quantity INTEGER NOT NULL,
    unit_codes TEXT,
    reference_email VARCHAR(320),
    status VARCHAR(24) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_stock_reservation_business FOREIGN KEY (business_id) REFERENCES businesses(id),
    CONSTRAINT fk_stock_reservation_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_stock_reservation_transaction FOREIGN KEY (transaction_id) REFERENCES inventory_transactions(id),
    CONSTRAINT uk_stock_reservation_payment_product UNIQUE (payment_reference, product_id),
    CONSTRAINT chk_stock_reservation_quantity CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_reservation_expiry
    ON stock_reservations (status, expires_at);
CREATE INDEX IF NOT EXISTS idx_stock_reservation_business_status
    ON stock_reservations (business_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_reservation_transaction
    ON stock_reservations (transaction_id);

CREATE TABLE IF NOT EXISTS ticket_reservations (
    id VARCHAR(64) PRIMARY KEY,
    business_id BIGINT,
    event_id VARCHAR(64) NOT NULL,
    ticket_type_id VARCHAR(64) NOT NULL,
    payment_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    quantity INTEGER NOT NULL,
    status VARCHAR(24) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_ticket_reservation_business FOREIGN KEY (business_id) REFERENCES businesses(id),
    CONSTRAINT fk_ticket_reservation_event FOREIGN KEY (event_id) REFERENCES ticket_events(id),
    CONSTRAINT fk_ticket_reservation_type FOREIGN KEY (ticket_type_id) REFERENCES event_ticket_types(id),
    CONSTRAINT fk_ticket_reservation_payment FOREIGN KEY (payment_id) REFERENCES ticket_payments(id),
    CONSTRAINT uk_ticket_reservation_payment UNIQUE (payment_id),
    CONSTRAINT chk_ticket_reservation_quantity CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_ticket_reservation_expiry
    ON ticket_reservations (status, expires_at);
CREATE INDEX IF NOT EXISTS idx_ticket_reservation_event_type
    ON ticket_reservations (event_id, ticket_type_id, status);

CREATE TABLE IF NOT EXISTS outbox_events (
    id VARCHAR(64) PRIMARY KEY,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id VARCHAR(128),
    event_type VARCHAR(96) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(24) NOT NULL,
    deduplication_key VARCHAR(180) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 10,
    available_at TIMESTAMP NOT NULL,
    locked_at TIMESTAMP,
    processed_at TIMESTAMP,
    last_error VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_outbox_deduplication_key UNIQUE (deduplication_key)
);

CREATE INDEX IF NOT EXISTS idx_outbox_dispatch
    ON outbox_events (status, available_at, created_at);
CREATE INDEX IF NOT EXISTS idx_outbox_aggregate
    ON outbox_events (aggregate_type, aggregate_id, created_at DESC);

CREATE TABLE IF NOT EXISTS generated_qr_assets (
    id VARCHAR(64) PRIMARY KEY,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id VARCHAR(128) NOT NULL,
    qr_value_hash VARCHAR(64) NOT NULL,
    object_name VARCHAR(512),
    public_url VARCHAR(2048),
    content_base64 TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_generated_qr_aggregate UNIQUE (aggregate_type, aggregate_id, qr_value_hash)
);

CREATE INDEX IF NOT EXISTS idx_generated_qr_aggregate_created
    ON generated_qr_assets (aggregate_type, aggregate_id, created_at DESC);

CREATE TABLE IF NOT EXISTS generated_reports (
    id VARCHAR(64) PRIMARY KEY,
    business_id BIGINT NOT NULL,
    report_type VARCHAR(80) NOT NULL,
    payload TEXT NOT NULL,
    generated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_generated_report_business FOREIGN KEY (business_id) REFERENCES businesses(id)
);

CREATE INDEX IF NOT EXISTS idx_generated_reports_business_type
    ON generated_reports (business_id, report_type, generated_at DESC);

ALTER TABLE event_ticket_types ADD COLUMN IF NOT EXISTS reserved INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ticket_events ADD COLUMN IF NOT EXISTS business_id BIGINT;
ALTER TABLE ticket_payments ADD COLUMN IF NOT EXISTS business_id BIGINT;
ALTER TABLE user_tickets ADD COLUMN IF NOT EXISTS business_id BIGINT;
ALTER TABLE user_tickets ADD COLUMN IF NOT EXISTS payment_id VARCHAR(64);
ALTER TABLE user_tickets ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE user_tickets ALTER COLUMN qr_code_value DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_tickets_qr_value
    ON user_tickets (qr_code_value);
CREATE INDEX IF NOT EXISTS idx_user_tickets_payment_status
    ON user_tickets (payment_id, status);
CREATE INDEX IF NOT EXISTS idx_user_tickets_business_status
    ON user_tickets (business_id, status, purchased_at DESC);
CREATE INDEX IF NOT EXISTS idx_ticket_events_business_status_date
    ON ticket_events (business_id, status, event_date);
CREATE INDEX IF NOT EXISTS idx_ticket_payments_reference_status
    ON ticket_payments (payment_reference, status);
CREATE INDEX IF NOT EXISTS idx_ticket_payments_business_created
    ON ticket_payments (business_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_products_business_status_stock
    ON products (business_id, status, stock_quantity);
CREATE INDEX IF NOT EXISTS idx_product_barcodes_product_availability
    ON product_barcodes (product_id, availability_status);
CREATE INDEX IF NOT EXISTS idx_product_barcodes_reference
    ON product_barcodes (reference_email);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_business_payment_date
    ON inventory_transactions (business_id, payment_status, date DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_payment_reference
    ON inventory_transactions (payment_reference);
CREATE INDEX IF NOT EXISTS idx_tips_worker_status_created
    ON tips (worker_id, status, created DESC);
CREATE INDEX IF NOT EXISTS idx_business_account_ledger_provider_lookup
    ON business_account_ledger_entries (provider, provider_reference, status);
CREATE INDEX IF NOT EXISTS idx_paypal_webhook_event_status_created
    ON paypal_webhook_events (paypal_event_id, status, created_date);
CREATE INDEX IF NOT EXISTS idx_stripe_webhook_event_status_created
    ON stripe_webhook_events (stripe_event_id, status, created_date);
