create table affiliate_links (
	id bigint generated by default as identity primary key,
	title varchar(160) not null,
	description varchar(512),
	affiliate_url varchar(2048) not null,
	image_url varchar(2048),
	website_name varchar(120) not null,
	category varchar(120),
	placement varchar(64) not null,
	status varchar(32) not null,
	priority integer not null default 1,
	display_for_free_trial boolean not null default true,
	display_for_plus boolean not null default true,
	display_for_pro boolean not null default false,
	impression_count bigint not null default 0,
	click_count bigint not null default 0,
	created_date timestamp not null,
	modified_date timestamp not null
);

create index idx_affiliate_links_status_placement on affiliate_links (status, placement);
create index idx_affiliate_links_category on affiliate_links (category);
