create table if not exists developer_hub_software_requests (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    business_id bigint not null,
    business_name varchar(255) not null,
    owner_name varchar(255) not null,
    owner_email varchar(255) not null,
    software_name varchar(160) not null,
    software_description varchar(4000) not null,
    requires_cloud_maintenance boolean not null,
    requires_quality_assurance_regression boolean not null,
    stage varchar(32) not null,
    status varchar(32) not null,
    admin_note varchar(2000),
    requested_at timestamp not null,
    updated_at timestamp not null,
    started_at timestamp,
    quote_sent_at timestamp,
    constraint fk_dev_hub_requests_owner foreign key (owner_id) references tracker_users (id),
    constraint fk_dev_hub_requests_business foreign key (business_id) references businesses (id)
);

create index if not exists idx_dev_hub_requests_business_requested on developer_hub_software_requests (business_id, requested_at desc);
create index if not exists idx_dev_hub_requests_owner_requested on developer_hub_software_requests (owner_id, requested_at desc);
create index if not exists idx_dev_hub_requests_stage_status on developer_hub_software_requests (stage, status);
