create table audit_logs (
	id bigint generated by default as identity primary key,
	action varchar(128) not null,
	entity_type varchar(128) not null,
	entity_id varchar(128),
	actor_username varchar(255) not null,
	details varchar(1000),
	created_at timestamp not null
);

create index idx_audit_logs_created_at on audit_logs (created_at);
create index idx_audit_logs_actor_username on audit_logs (actor_username);
