create table product_barcodes (
	id bigint generated by default as identity primary key,
	product_id bigint not null,
	barcode varchar(255) not null,
	constraint uk_product_barcodes_barcode unique (barcode),
	constraint fk_product_barcodes_product foreign key (product_id) references products (id)
);

insert into product_barcodes (product_id, barcode)
select id, barcode
from products
where barcode is not null;

alter table products alter column barcode drop not null;

create index idx_product_barcodes_product_id on product_barcodes (product_id);
