create table subscribers (
    id bigint generated by default as identity primary key,
    contact_value varchar(320) not null unique,
    contact_type varchar(24) not null,
    subscriber_type varchar(32) not null,
    preferred_channel varchar(16) not null,
    active boolean not null,
    source varchar(64) not null,
    last_notified_at timestamp with time zone,
    created_date timestamp with time zone not null,
    modified_date timestamp with time zone not null
);

create table promotions (
    id bigint generated by default as identity primary key,
    business_id bigint,
    title varchar(160) not null,
    message varchar(2000) not null,
    landing_url varchar(2048),
    origin varchar(32) not null,
    channel varchar(16) not null,
    status varchar(16) not null,
    target_count integer not null,
    bulk_price numeric(12, 2) not null,
    created_by varchar(255) not null,
    scheduled_for timestamp with time zone not null,
    expires_at timestamp with time zone,
    last_processed_at timestamp with time zone,
    created_date timestamp with time zone not null,
    modified_date timestamp with time zone not null,
    constraint fk_promotions_business foreign key (business_id) references businesses (id)
);

create table promotion_notifications (
    id bigint generated by default as identity primary key,
    promotion_id bigint not null,
    subscriber_id bigint not null,
    channel varchar(16) not null,
    status varchar(32) not null,
    failure_reason varchar(1000),
    created_date timestamp with time zone not null,
    constraint fk_promotion_notifications_promotion foreign key (promotion_id) references promotions (id),
    constraint fk_promotion_notifications_subscriber foreign key (subscriber_id) references subscribers (id)
);

create index idx_subscribers_active_last_notified on subscribers (active, last_notified_at);
create index idx_subscribers_contact_type on subscribers (contact_type);
create index idx_promotions_status_scheduled_for on promotions (status, scheduled_for);
create index idx_promotions_business_id on promotions (business_id);
create unique index uk_promotion_notifications_promotion_subscriber on promotion_notifications (promotion_id, subscriber_id);
