name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Build backend Docker image
        run: docker build --pull -t king-sparkon-tracker-backend:${{ github.sha }} .
      - name: Inspect backend Docker image
        run: docker image inspect king-sparkon-tracker-backend:${{ github.sha }}
